{
 "title": "Service Weaver Dashboard",
 "description": "Basic Service Weaver dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# Method Invocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "serviceweaver_method_count" }
   ]
  },
  {
   "title": "# Method Invocations with errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "serviceweaver_method_error_count"
    }
   ]
  },
  {
   "title": "Distribution of latency (us) of Service Weaver component execution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "serviceweaver_method_latency_micros_bucket"
    }
   ]
  },
  {
   "title": "Distribution of #bytes in Service Weaver component method requests",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "serviceweaver_method_bytes_request_bucket"
    }
   ]
  },
  {
   "title": "Distribution of #bytes in Service Weaver component method replies",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "serviceweaver_method_bytes_reply_bucket"
    }
   ]
  }
 ]
}