// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: internal/impl/k8s.proto

package impl

import (
	protos "github.com/ServiceWeaver/weaver/runtime/protos"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReplicaSetConfig contains app deployment information that is needed by a
// babysitter started using the K8s deployer to manage a set of components.
type ReplicaSetConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deployment        *protos.Deployment                     `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	ReplicaSet        string                                 `protobuf:"bytes,2,opt,name=replica_set,json=replicaSet,proto3" json:"replica_set,omitempty"`
	ComponentsToStart map[string]*ReplicaSetConfig_Listeners `protobuf:"bytes,3,rep,name=components_to_start,json=componentsToStart,proto3" json:"components_to_start,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	InternalPort      int32                                  `protobuf:"varint,4,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
}

func (x *ReplicaSetConfig) Reset() {
	*x = ReplicaSetConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_impl_k8s_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicaSetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaSetConfig) ProtoMessage() {}

func (x *ReplicaSetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_impl_k8s_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaSetConfig.ProtoReflect.Descriptor instead.
func (*ReplicaSetConfig) Descriptor() ([]byte, []int) {
	return file_internal_impl_k8s_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicaSetConfig) GetDeployment() *protos.Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *ReplicaSetConfig) GetReplicaSet() string {
	if x != nil {
		return x.ReplicaSet
	}
	return ""
}

func (x *ReplicaSetConfig) GetComponentsToStart() map[string]*ReplicaSetConfig_Listeners {
	if x != nil {
		return x.ComponentsToStart
	}
	return nil
}

func (x *ReplicaSetConfig) GetInternalPort() int32 {
	if x != nil {
		return x.InternalPort
	}
	return 0
}

type ReplicaSetConfig_Listeners struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Listeners []*ReplicaSetConfig_Listener `protobuf:"bytes,1,rep,name=listeners,proto3" json:"listeners,omitempty"`
}

func (x *ReplicaSetConfig_Listeners) Reset() {
	*x = ReplicaSetConfig_Listeners{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_impl_k8s_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicaSetConfig_Listeners) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaSetConfig_Listeners) ProtoMessage() {}

func (x *ReplicaSetConfig_Listeners) ProtoReflect() protoreflect.Message {
	mi := &file_internal_impl_k8s_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaSetConfig_Listeners.ProtoReflect.Descriptor instead.
func (*ReplicaSetConfig_Listeners) Descriptor() ([]byte, []int) {
	return file_internal_impl_k8s_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ReplicaSetConfig_Listeners) GetListeners() []*ReplicaSetConfig_Listener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

type ReplicaSetConfig_Listener struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExternalPort int32  `protobuf:"varint,2,opt,name=external_port,json=externalPort,proto3" json:"external_port,omitempty"`
}

func (x *ReplicaSetConfig_Listener) Reset() {
	*x = ReplicaSetConfig_Listener{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_impl_k8s_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicaSetConfig_Listener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaSetConfig_Listener) ProtoMessage() {}

func (x *ReplicaSetConfig_Listener) ProtoReflect() protoreflect.Message {
	mi := &file_internal_impl_k8s_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaSetConfig_Listener.ProtoReflect.Descriptor instead.
func (*ReplicaSetConfig_Listener) Descriptor() ([]byte, []int) {
	return file_internal_impl_k8s_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ReplicaSetConfig_Listener) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReplicaSetConfig_Listener) GetExternalPort() int32 {
	if x != nil {
		return x.ExternalPort
	}
	return 0
}

var File_internal_impl_k8s_proto protoreflect.FileDescriptor

var file_internal_impl_k8s_proto_rawDesc = []byte{
	0x0a, 0x17, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6d, 0x70, 0x6c, 0x2f,
	0x6b, 0x38, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x69, 0x6d, 0x70, 0x6c, 0x1a,
	0x1b, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe5, 0x03, 0x0a,
	0x10, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x33, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x12, 0x5d, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x74, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x69, 0x6d, 0x70, 0x6c, 0x2e, 0x52, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6d,
	0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x54, 0x6f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x11, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x54,
	0x6f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x1a, 0x4a, 0x0a, 0x09, 0x4c,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x3d, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69, 0x6d,
	0x70, 0x6c, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x52, 0x09, 0x6c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x1a, 0x43, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x1a, 0x66, 0x0a, 0x16,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x54, 0x6f, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x36, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69, 0x6d, 0x70, 0x6c, 0x2e, 0x52,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x57, 0x65, 0x61, 0x76, 0x65, 0x72,
	0x2f, 0x77, 0x65, 0x61, 0x76, 0x65, 0x72, 0x2d, 0x6b, 0x38, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6d, 0x70, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_internal_impl_k8s_proto_rawDescOnce sync.Once
	file_internal_impl_k8s_proto_rawDescData = file_internal_impl_k8s_proto_rawDesc
)

func file_internal_impl_k8s_proto_rawDescGZIP() []byte {
	file_internal_impl_k8s_proto_rawDescOnce.Do(func() {
		file_internal_impl_k8s_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_impl_k8s_proto_rawDescData)
	})
	return file_internal_impl_k8s_proto_rawDescData
}

var file_internal_impl_k8s_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_impl_k8s_proto_goTypes = []interface{}{
	(*ReplicaSetConfig)(nil),           // 0: impl.ReplicaSetConfig
	(*ReplicaSetConfig_Listeners)(nil), // 1: impl.ReplicaSetConfig.Listeners
	(*ReplicaSetConfig_Listener)(nil),  // 2: impl.ReplicaSetConfig.Listener
	nil,                                // 3: impl.ReplicaSetConfig.ComponentsToStartEntry
	(*protos.Deployment)(nil),          // 4: runtime.Deployment
}
var file_internal_impl_k8s_proto_depIdxs = []int32{
	4, // 0: impl.ReplicaSetConfig.deployment:type_name -> runtime.Deployment
	3, // 1: impl.ReplicaSetConfig.components_to_start:type_name -> impl.ReplicaSetConfig.ComponentsToStartEntry
	2, // 2: impl.ReplicaSetConfig.Listeners.listeners:type_name -> impl.ReplicaSetConfig.Listener
	1, // 3: impl.ReplicaSetConfig.ComponentsToStartEntry.value:type_name -> impl.ReplicaSetConfig.Listeners
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_impl_k8s_proto_init() }
func file_internal_impl_k8s_proto_init() {
	if File_internal_impl_k8s_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_impl_k8s_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicaSetConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_impl_k8s_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicaSetConfig_Listeners); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_impl_k8s_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicaSetConfig_Listener); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_impl_k8s_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_impl_k8s_proto_goTypes,
		DependencyIndexes: file_internal_impl_k8s_proto_depIdxs,
		MessageInfos:      file_internal_impl_k8s_proto_msgTypes,
	}.Build()
	File_internal_impl_k8s_proto = out.File
	file_internal_impl_k8s_proto_rawDesc = nil
	file_internal_impl_k8s_proto_goTypes = nil
	file_internal_impl_k8s_proto_depIdxs = nil
}
