// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: internal/impl/kube.proto

package impl

import (
	protos "github.com/ServiceWeaver/weaver/runtime/protos"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReplicaSetConfig contains app deployment information that is needed by a
// babysitter started using the kube deployer to manage a set of components.
type ReplicaSetConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace       string                        `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name            string                        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DepId           string                        `protobuf:"bytes,3,opt,name=dep_id,json=depId,proto3" json:"dep_id,omitempty"`
	App             *protos.AppConfig             `protobuf:"bytes,4,opt,name=app,proto3" json:"app,omitempty"`
	InternalPort    int32                         `protobuf:"varint,5,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	TraceServiceUrl string                        `protobuf:"bytes,6,opt,name=trace_service_url,json=traceServiceUrl,proto3" json:"trace_service_url,omitempty"`
	Components      []*ReplicaSetConfig_Component `protobuf:"bytes,7,rep,name=components,proto3" json:"components,omitempty"`
}

func (x *ReplicaSetConfig) Reset() {
	*x = ReplicaSetConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_impl_kube_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicaSetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaSetConfig) ProtoMessage() {}

func (x *ReplicaSetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_impl_kube_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaSetConfig.ProtoReflect.Descriptor instead.
func (*ReplicaSetConfig) Descriptor() ([]byte, []int) {
	return file_internal_impl_kube_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicaSetConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ReplicaSetConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReplicaSetConfig) GetDepId() string {
	if x != nil {
		return x.DepId
	}
	return ""
}

func (x *ReplicaSetConfig) GetApp() *protos.AppConfig {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *ReplicaSetConfig) GetInternalPort() int32 {
	if x != nil {
		return x.InternalPort
	}
	return 0
}

func (x *ReplicaSetConfig) GetTraceServiceUrl() string {
	if x != nil {
		return x.TraceServiceUrl
	}
	return ""
}

func (x *ReplicaSetConfig) GetComponents() []*ReplicaSetConfig_Component {
	if x != nil {
		return x.Components
	}
	return nil
}

// Components hosted by the replica sets, and their network listeners.
type ReplicaSetConfig_Component struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Listeners []*ReplicaSetConfig_Listener `protobuf:"bytes,2,rep,name=listeners,proto3" json:"listeners,omitempty"`
}

func (x *ReplicaSetConfig_Component) Reset() {
	*x = ReplicaSetConfig_Component{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_impl_kube_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicaSetConfig_Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaSetConfig_Component) ProtoMessage() {}

func (x *ReplicaSetConfig_Component) ProtoReflect() protoreflect.Message {
	mi := &file_internal_impl_kube_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaSetConfig_Component.ProtoReflect.Descriptor instead.
func (*ReplicaSetConfig_Component) Descriptor() ([]byte, []int) {
	return file_internal_impl_kube_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ReplicaSetConfig_Component) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReplicaSetConfig_Component) GetListeners() []*ReplicaSetConfig_Listener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

type ReplicaSetConfig_Listener struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ServiceName  string `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ExternalPort int32  `protobuf:"varint,3,opt,name=external_port,json=externalPort,proto3" json:"external_port,omitempty"`
	IsPublic     bool   `protobuf:"varint,4,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
}

func (x *ReplicaSetConfig_Listener) Reset() {
	*x = ReplicaSetConfig_Listener{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_impl_kube_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicaSetConfig_Listener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaSetConfig_Listener) ProtoMessage() {}

func (x *ReplicaSetConfig_Listener) ProtoReflect() protoreflect.Message {
	mi := &file_internal_impl_kube_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaSetConfig_Listener.ProtoReflect.Descriptor instead.
func (*ReplicaSetConfig_Listener) Descriptor() ([]byte, []int) {
	return file_internal_impl_kube_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ReplicaSetConfig_Listener) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReplicaSetConfig_Listener) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ReplicaSetConfig_Listener) GetExternalPort() int32 {
	if x != nil {
		return x.ExternalPort
	}
	return 0
}

func (x *ReplicaSetConfig_Listener) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

var File_internal_impl_kube_proto protoreflect.FileDescriptor

var file_internal_impl_kube_proto_rawDesc = []byte{
	0x0a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6d, 0x70, 0x6c, 0x2f,
	0x6b, 0x75, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x69, 0x6d, 0x70, 0x6c,
	0x1a, 0x1b, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfa, 0x03,
	0x0a, 0x10, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x65, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x70, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x03, 0x61,
	0x70, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x03, 0x61, 0x70,
	0x70, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55,
	0x72, 0x6c, 0x12, 0x40, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69, 0x6d, 0x70, 0x6c, 0x2e, 0x52, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x73, 0x1a, 0x5e, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69, 0x6d, 0x70, 0x6c, 0x2e,
	0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x52, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x73, 0x1a, 0x83, 0x01, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x69, 0x73, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x69, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x57, 0x65, 0x61, 0x76, 0x65, 0x72, 0x2f, 0x77, 0x65, 0x61, 0x76, 0x65, 0x72, 0x2d, 0x6b, 0x75,
	0x62, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6d, 0x70, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_impl_kube_proto_rawDescOnce sync.Once
	file_internal_impl_kube_proto_rawDescData = file_internal_impl_kube_proto_rawDesc
)

func file_internal_impl_kube_proto_rawDescGZIP() []byte {
	file_internal_impl_kube_proto_rawDescOnce.Do(func() {
		file_internal_impl_kube_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_impl_kube_proto_rawDescData)
	})
	return file_internal_impl_kube_proto_rawDescData
}

var file_internal_impl_kube_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_impl_kube_proto_goTypes = []interface{}{
	(*ReplicaSetConfig)(nil),           // 0: impl.ReplicaSetConfig
	(*ReplicaSetConfig_Component)(nil), // 1: impl.ReplicaSetConfig.Component
	(*ReplicaSetConfig_Listener)(nil),  // 2: impl.ReplicaSetConfig.Listener
	(*protos.AppConfig)(nil),           // 3: runtime.AppConfig
}
var file_internal_impl_kube_proto_depIdxs = []int32{
	3, // 0: impl.ReplicaSetConfig.app:type_name -> runtime.AppConfig
	1, // 1: impl.ReplicaSetConfig.components:type_name -> impl.ReplicaSetConfig.Component
	2, // 2: impl.ReplicaSetConfig.Component.listeners:type_name -> impl.ReplicaSetConfig.Listener
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_impl_kube_proto_init() }
func file_internal_impl_kube_proto_init() {
	if File_internal_impl_kube_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_impl_kube_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicaSetConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_impl_kube_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicaSetConfig_Component); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_impl_kube_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicaSetConfig_Listener); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_impl_kube_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_impl_kube_proto_goTypes,
		DependencyIndexes: file_internal_impl_kube_proto_depIdxs,
		MessageInfos:      file_internal_impl_kube_proto_msgTypes,
	}.Build()
	File_internal_impl_kube_proto = out.File
	file_internal_impl_kube_proto_rawDesc = nil
	file_internal_impl_kube_proto_goTypes = nil
	file_internal_impl_kube_proto_depIdxs = nil
}
